name: tux_keytool
description: "Key generator for GoogleApp"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  country_list_pick: ^1.0.1+6
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  process: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
